import = ["$HOME/.config/alacritty/tokyonignt_storm.toml"]

[colors]
draw_bold_text_with_bright_colors = false

[cursor.style]
blinking = "Off"
shape = "Block"

[font]
size = 16.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Retina"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001C1"
key = "Key1"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001C2"
key = "Key2"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001C3"
key = "Key3"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001C4"
key = "Key4"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001C5"
key = "Key5"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001C6"
key = "Key6"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001C7"
key = "Key7"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001C8"
key = "Key8"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001C9"
key = "Key9"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Cc"
key = "T"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BF"
key = "F"
mods = "Alt"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 1000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "full"
dynamic_title = true
opacity = 0.8
startup_mode = "Maximized"
