# export LANG=zh_CN.uft8
export LC_ALL=zh_CN.UTF-8

source ~/.dotfiles/.env

for file in ~/.dotfiles/zsh/*.sh; do
  if [ -d "$file" ]; then
    echo "$file is directory"
  elif [ -f "$file" ]; then
    # echo "$file is file"
    source $file
  fi
done


# ZSH config
bindkey '^n' end-of-line

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
DISABLE_AUTO_UPDATE='true'
ZSH_DISABLE_COMPFIX='true'
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME='hjkl01'
# ZSH_THEME='robbyrussell'
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  # git
  zsh-autosuggestions
  zsh-syntax-highlighting
  web-search
  zsh-you-should-use
)
source $HOME/.oh-my-zsh/oh-my-zsh.sh

# fpath=(~/.oh-my-zsh/custom/plugins/zsh-completions/src $fpath)
# rm -f ~/.zcompdump; compinit

source $HOME/.dotfiles/zsh/alias.zsh

setopt NO_HUP

# export TERM="screen-256color"
# tmux.conf handles TERM setting; only set for non-tmux sessions
[ -z "$TMUX" ] && export TERM="xterm-256color"

alias run_tmux='tmux -f ~/.dotfiles/config/tmux.conf -u'
if [[ "${START_TMUX:-0}" == "1" && -z "$TMUX" ]]; then
  tmux attach || run_tmux
fi

alias run_zellij='zellij attach main || zellij -s main'
if [[ "${START_ZELLIJ:-0}" == "1" && -z "$ZELLIJ" ]] && command -v zellij &>/dev/null; then
  zellij attach main || zellij -s main
fi
